---
title: "Assignment: Probability Distributions in R"
author: "Callum Feher"
date: "1/19/15"
output: html_document
---

### Continuous

#### Probability

```{r}
pnorm(1.25)
pnorm(2.8, 2, 3)
pchisq(13.9, 25)
1 - pexp(4, 10)
pexp(4, 10, lower.tail=FALSE)
pt(3.9, 7)

```

#### Quantiles

```{r}
qnorm(.25)
qnorm(.75, 2,3)
qt(.975, 13)

```

#### Random Numbers

```{r}
rnorm(100)
x <- rnorm(100)
hist(x)
rchisq(10, 23)

```

#### Plotting the Density Curve (pdf)

```{r}
curve(dnorm(x), from = -3, to = -3)
w <- rnorm(50)
hist(w, freq = TRUE)
curve(dnorm(x), add = TRUE)
hist(w, freq = TRUE, ylim = c(0, .5))
curve(dnorm(x), add=TRUE)

```

### Discrete

#### Example--Binomial

```{r}
dbinom(5,16, .8)
choose(16,5)*.8^5*.2^11
pbinom(5,16,.8)
dbinom(0,16,.8)+dbinom(1,16,.8)+dbinom(2,16,.8)+dbinom(3,16,.8)+dbinom(4,16,.8)+dbinom(5,16,.8)
qbinom(.25,16,.8)
pbinom(11, 16, .8)
pbinom(12, 16, .8)

```

#### Example--Geometric

```{r}
dgeom(3,.8)
pgeom(3,.8)

```

#### Example--Poisson

```{r}
dpois(3,5)
5^3*exp(-5)/(3*2)

```

#### Random Numbers

```{r}
# This code simulates 25 flips of a biased coin where P(Head) = 0.8 or 80%.
# The output is the total count of heads (or successes) in those 25 flips.
rbinom(1,25,.8)

# This value seeds the pseudo-random number generator in R. It is optional.
# Anyone using the same seed value will generate identical "random" values.
set.seed(0)

# This code simulates 25 flips of a biased coin where P(Head) = 0.8 or 80%.
# The experiment is repeated 10 times; output is the total number of heads.
# There will be a total of ten values, one for each repetition of 25 flips.
# Those ten values will be stored in a vector called "heads".
heads <- rbinom(10, 25, .8)

# This code prints out the values in the vector heads.
heads

# This code creates a frequency table of the values in the vector heads.  
table(heads)

# This code creates a bar chart of the values in the vector heads.
barplot(table(heads))

# This code simulates 25 flips of a biased coin where P(Head) = 0.8 or 80%.
# The experiment is repeated 100 times; output is the total number of heads.
# There will be a total of 100 values, one for each repetition of 25 flips.
# Those 100 values will be stored in a vector called "heads2".
heads2 <- rbinom(100, 25, .8)

# This code prints out the values in the vector heads2.
heads2

# This code creates a frequency table of the values in the vector heads2. 
table(heads2)

# This code creates a bar chart of the values in the vector heads.
barplot(table(heads2))
```